version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local:2.0.0
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211:11211"
    restart: always
  mysql:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "forge"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    restart: always
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_PASSWORD: "secret"
  #     POSTGRES_DB: "forge"
  #   ports:
  #     - "5432:5432"
  #   restart: always
  # mariadb:
  #   image: mariadb:11
  #   environment:
  #     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
  #     MARIADB_ROOT_PASSWORD: ""
  #     MARIADB_DATABASE: "forge"
  #     MARIADB_ROOT_HOST: "%"
  #   ports:
  #     - "3306:3306"
  #   restart: always
  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     ACCEPT_EULA: "Y"
  #     SA_PASSWORD: "Forge123"
  #   ports:
  #     - "1433:1433"
  #   restart: always
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    restart: always
